version: '3.9'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
  #   # environment:
  #   #  - DATABASE_HOST=db
  #   volumes:
  #     - .:.
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 6000:3306
